/**
 * Write docs/proofs/live.md from docs/proofs/live.json, the record the live
 * proofs left. Nothing in the page is typed by hand: every check, hash, model
 * and vote comes from the record, so the page cannot drift from the run.
 *
 *   node scripts/proofs-report.mjs                 the deployment of record
 *   node scripts/proofs-report.mjs --label dev     a disposable run, into .data/
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const at = (rel) => fileURLToPath(new URL(rel, import.meta.url));
const flag = process.argv.indexOf("--label");
const label = flag > 0 ? process.argv[flag + 1] : "";
const paths = label
  ? { live: `../.data/proofs-${label}.json`, record: `../.data/deployments/${label}.json`, page: `../.data/proofs-${label}.md` }
  : { live: "../docs/proofs/live.json", record: "../deployments/record.json", page: "../docs/proofs/live.md" };
const live = JSON.parse(readFileSync(at(paths.live), "utf-8"));
const record = JSON.parse(readFileSync(at(paths.record), "utf-8"));
const explorer = "https://explorer-studio-dev.genlayer.com";

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
  "November", "December"];
const when = (iso) => {
  const d = new Date(iso);
  const hm = `${String(d.getUTCHours()).padStart(2, "0")}:${String(d.getUTCMinutes()).padStart(2, "0")}`;
  return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}, ${hm} UTC`;
};
const cell = (v) => String(v ?? "").replace(/\|/g, "/").replace(/\s+/g, " ").trim();
const short = (v, n = 220) => (cell(v).length > n ? `${cell(v).slice(0, n)} ...` : cell(v));
const tx = (hash) => `[\`${hash.slice(0, 10)}...${hash.slice(-6)}\`](${explorer}/tx/${hash})`;

const CASES = {
  F: "a declined case", G: "a withdrawn case", T: "terms the contract refuses", A: "the synthetic sample",
  D: "one word against another", B: "a claim the records bear out", C: "a planted instruction",
  E: "required evidence missing, with an inspector", N: "nothing filed", S: "a file brought from another dispute",
  I: "a follow-up case", withdraw: "withdrawals", ledger: "the ledger",
};

const lines = [];
const out = (s = "") => lines.push(s);

out("# Live proofs on Studio Next");
out();
out("Generated by `scripts/proofs-report.mjs` from `docs/proofs/live.json`, the record `scripts/proofs.mjs --record`");
out("left when it ran. Nothing here is typed by hand. Every transaction below was signed by a separate test wallet and");
out("judged or executed by Studio Next's validators, and every check reads the contract's own state.");
out();
out("| | |");
out("|---|---|");
out(`| Contract | [\`${record.contract}\`](${explorer}/address/${record.contract}) |`);
out(`| Network | ${record.network}, chain ${record.chain_id} |`);
out(`| Source | \`${record.source}\`, sha256 \`${record.source_sha256}\` (the code the network stores hashes to the same value) |`);
out(`| Deployed | ${when(record.deployed_at)}, transaction ${tx(record.deploy_tx)} |`);
out(`| Run | started ${when(live.started)}, finished ${when(live.finished)} |`);
out(`| Result | **${live.summary.passed} of ${live.summary.checks} checks passed**${live.summary.failed.length ? `; failed: ${live.summary.failed.map(cell).join("; ")}` : ""} |`);
out();
out("To run it again against a fresh deployment (about 75 minutes, mostly waiting out real windows):");
out();
out("```bash");
out("node scripts/deploy.mjs --label again");
out("cd scripts && node --experimental-strip-types --import ./ts-loader.mjs proofs.mjs --label again");
out("```");
out();

out("## The wallets");
out();
out("Test wallets generated for this run. Each role signs its own transactions; no key is shared.");
out();
out("| Role in the run | Address |");
out("|---|---|");
for (const [role, addr] of Object.entries(live.wallets ?? {})) out(`| ${role.toLowerCase()} | \`${addr}\` |`);
out();

out("## Every check");
out();
out("| | Check | What was observed |");
out("|---|---|---|");
for (const c of live.checks) out(`| ${c.ok ? "pass" : "**FAIL**"} | ${cell(c.name)} | ${short(c.detail)} |`);
out();

out("## The assessments, node by node");
out();
out("For each transaction that asked validators to judge a case: every consensus round, which model each node ran,");
out("whether its model read the calibration image (\"sees\"), how it voted, and why it dissented when it did. A leader");
out("that could not read the calibration image fails its round, and the network rotates to another.");
out();
for (const [key, step] of Object.entries(live.steps)) {
  if (!step || !Array.isArray(step.attempts)) continue;
  const name = CASES[key.split(".")[0]] ?? key;
  out(`### ${key} (${name})`);
  out();
  out(`Recorded: ${cell(JSON.stringify(step.returned))}`);
  out();
  step.attempts.forEach((a, i) => {
    out(`Attempt ${i + 1}: ${tx(a.hash)}, ${cell(a.status)}${a.consensus ? `, ${cell(a.consensus)}` : ""}`
      + `${a.final_status ? `, then ${cell(a.final_status)}` : ""}${a.appeal ? `; protocol appeal ${a.appeal.sent ? `sent (charge ${cell(a.appeal.charge)} atto)` : `not sent: ${cell(a.appeal.why)}`}` : ""}`);
    out();
    out("| Round | Node | Model | Sees | Vote | Dissent |");
    out("|---|---|---|---|---|---|");
    for (const r of a.votes?.rounds ?? []) {
      for (const n of r.nodes) {
        if (n.model === "/?" && !n.vote) continue;
        out(`| ${cell(r.round)} | ${cell(n.mode)} | ${cell(n.model === "/?" ? "not reported" : n.model)} | `
          + `${n.sighted === true ? "yes" : n.sighted === false ? "no" : ""} | ${cell(n.vote || (n.mode === "leader" ? "led" : ""))} | ${short(n.dissent, 140)} |`);
      }
    }
    out();
  });
}

out("## Every transaction");
out();
out("In the order the run made them. \"Refused\" rows are transactions the contract was expected to refuse, with the");
out("reason it gave.");
out();
out("| Step | Signed by | Method | Result | Transaction |");
out("|---|---|---|---|---|");
for (const { key } of live.log) {
  const step = live.steps[key];
  if (!step || typeof step !== "object" || !step.hash) continue;
  let result = "recorded";
  if (step.refusal !== undefined) result = step.executed ? "executed" : `refused: ${short(step.refusal, 150)}`;
  else if (step.returned?.refused) result = `refused by returning, value credited back: ${short(step.returned.reason, 120)}`;
  else if (Array.isArray(step.attempts)) result = `decision ${cell(step.returned?.decision_id)}: ${cell(step.returned?.overall).toLowerCase().replace(/_/g, " ")}`;
  out(`| ${cell(key)} | ${cell(step.by ?? "").toLowerCase()} | ${cell(step.method ?? "")} | ${result} | ${tx(step.hash)} |`);
}
out();

writeFileSync(at(paths.page), lines.join("\n"));
console.log(`${paths.page.slice(3)} written: ${live.checks.length} checks, ${lines.length} lines`);
